% 生成一些示例数据
rng(42);  % 设置随机种子，以便结果可重复
X = randn(100, 5);
y = randn(100, 1);

% 定义随机森林模型的参数
random_state = 90;




% 构建随机森林模型
rf_model = TreeBagger(181, X, y, ...
    'Method', 'regression', ...
    'NumPredictorsToSample', 4, ...
    'MaxNumSplits', 19, ...
    'MinLeafSize', 1, ...
    'MinLeaf', 2, ...
    'OOBPrediction', 'on', ...
    'Options', statset('UseParallel', true, 'UseSubstreams', true, 'Streams', rng(random_state)));

% 定义 LGBMRegressor 的参数
num_leaves = 91;
feature_fraction = 0.5;
bagging_fraction = 0.1;
bagging_freq = 0;
reg_alpha = 0.25;
reg_lambda = 0.0;
min_split_gain = 0;
random_state = 90;

% 构建 LGBMRegressor 类似的模型
lgbm_model = fitrensemble(X, y, ...
    'Method', 'LSBoost', ...
    'NumLearningCycles', 201, ...
    'Learners', templateTree('MaxNumSplits', 17, 'MinLeafSize', 1), ...
    'ModelParams', 'Tree', ...
    'NumBins', 90, ...
    'LearnRate', 0.1, ...
    'CategoricalPredictors', 'all', ...
    'LearnRate', 0.1, ...
    'OptimizeHyperparameters', 'all', ...
    'HyperparameterOptimizationOptions', struct('Optimizer', 'bayesopt', 'MaxObjectiveEvaluations', 30, 'UseParallel', true), ...
    'PredictorNames', strcat('Var', cellstr(num2str((1:size(X, 2))'))), ...
    'VariableSelection', 'allsplits', ...
    'Prune', 'on', ...
    'KFold', 5, ...
    'Verbose', 2);
